services:
  linktree:
    image: nginx:alpine
    container_name: linktree
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linktree.rule=Host(`appone.yourdomain.com`)"
      - "traefik.http.routers.linktree.entrypoints=websecure"
      - "traefik.http.routers.linktree.tls.certresolver=letsencrypt"
      - "traefik.http.routers.linktree.middlewares=authelia-auth@file"
    networks:
      - web

networks:
  web:
    external: true