services:
  traefik:
    image: traefik:v3.3
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CF_API_TOKEN} 
      - TZ=Europe/Madrid
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"  # Solo accesible desde tu red local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./dynamic:/dynamic:ro
      - ./acme.json:/acme.json
      - /var/log/traefik/access.log:/var/log/traefik/access.log
    networks:
      - web

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`auth.youtdomain.com`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls.certresolver=letsencrypt"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091" 
    volumes:
      - ./authelia:/config
    environment:
      - TZ=Europe/Madrid
    networks:
      - web

  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.yourdomain.com`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
      - "traefik.http.routers.whoami.middlewares=authelia-auth@file"
    networks:
      - web

networks:
  web:
    external: true
