http:
  middlewares:
    authelia-auth:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://auth.yourdomain.com"
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups

    appone-bouncer-traefik-plugin:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          CrowdsecLapiKey: "your_crowdsec_lapi_key"
          Enabled: "true"

    my-fail2ban:
      plugin:
        fail2ban:
          allowlist:
            ip:
              - "::1"
              - "127.0.0.1"
          denylist:
            ip:
              - "192.168.77.0/24"
          rules:
            bantime: "3h"
            enabled: "true"
            findtime: "10m"
            maxretry: "4"
            statuscode: "400,401,403-499"


